"""
Application configuration constants.

WHY: Centralizes configurable values for easy tuning without code changes.
"""

import os

CHAT_MESSAGE_HISTORY_LIMIT = 100
MAX_MESSAGES_PER_LOCATION = 100
MAX_MESSAGE_LENGTH = 5000
MAX_CHARACTERS_PER_USER = 10
MAX_CHARACTER_NAME_LENGTH = 100
MAX_CHARACTER_DESCRIPTION_LENGTH = 2000
MAX_LOCATION_NAME_LENGTH = 100
MAX_LOCATION_DESCRIPTION_LENGTH = 2000
MAX_USERNAME_LENGTH = 50
MIN_PASSWORD_LENGTH = 6
MAX_PASSWORD_LENGTH = 100
MIN_USERNAME_LENGTH = 3
MAX_AVATAR_URL_LENGTH = 500
MAX_BACKGROUND_URL_LENGTH = 500
MAX_EMAIL_LENGTH = 255

ACCESS_TOKEN_EXPIRE_DAYS = 7
TOKEN_REFRESH_THRESHOLD_DAYS = 3

DELETED_USER_DISPLAY_NAME = "Deleted User"
DELETED_CHARACTER_DISPLAY_NAME = "Deleted Character"
DELETED_SENDER_DISPLAY_NAME = "Deleted"
DEFAULT_AVATAR_PATH = "/static/assets/img/builtin_avatars/mtrx_avatar_default1.png"
DELETED_AVATAR_PATH = "/static/assets/img/builtin_avatars/deleted_avatar.png"

SECRET_KEY: str = os.getenv("SECRET_KEY", "")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable is required")

ALGORITHM: str = "HS256"

PUBLIC_CONFIG_KEYS = [
    "CHAT_MESSAGE_HISTORY_LIMIT",
    "MAX_MESSAGES_PER_LOCATION",
    "MAX_MESSAGE_LENGTH",
    "MAX_CHARACTER_NAME_LENGTH",
    "MAX_CHARACTER_DESCRIPTION_LENGTH",
    "MAX_LOCATION_NAME_LENGTH",
    "MAX_LOCATION_DESCRIPTION_LENGTH",
    "MAX_USERNAME_LENGTH",
    "MIN_PASSWORD_LENGTH",
    "MAX_PASSWORD_LENGTH",
    "MIN_USERNAME_LENGTH",
    "ACCESS_TOKEN_EXPIRE_DAYS",
]
